version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - run:
          name: dependencies
          command: |
            sudo apt update
            sudo apt install libgtk-3-dev libappindicator3-dev
      - run:
          name: build
          command: go build
      - run:
          name: upload_release
          command: |
            TAG=$(git describe --tags)
            mv yd-go yd-go-amd64
            ghr -t ${GHAPITOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${TAG} ./yd-go-amd64

workflows:
  version: 2.1
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
