version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run:
          name: dependencies
          command: sudo apt install libgtk-3-dev libappindicator3-dev
      - run:
          name: build
          command: go build
      - run:
          name: upload_release
          command: .circleci/upload_release.sh


workflows:
  version: 2
  build:
    jobs:
      - build