version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - run:
          name: dependencies
          command: |
            sudo apt update
            sudo apt install libgtk-3-dev libappindicator3-dev
      - run:
          name: build
          command: go build
      - run:
          name: prepare artifacts
          command: |
            git describe --tags > TAG
            mv yd-go yd-go-amd64
      - persist_to_workspace:
          root: .
          paths:
            - ./yd-go-amd64
            - ./TAG
  upload:
    docker:
      - image: 'cibuilds/github:0.10'
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: Publish Release on GitHub
          command: |
            TAG=$(cat ./artifacts/TAG)
            ghr -t ${GHAPITOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${TAG} ./artifacts/yd-go-amd64



workflows:
  version: 2.1
  build_upload:
    jobs:
      - build
      - upload:
          filters:
            branches:
              only: master
