version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.1
    steps:
      - checkout
      - run:
          name: test
          command: pwd
      - run:
          name: upload_release
          command: .circleci/upload_rerelease.sh


workflows:
  version: 2
  build:
    jobs:
      - build