name: Go
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Cache
        uses: actions/cache@v2.1.6
        with:
          path: |
            /home/runner/.cache/go-build/
            /home/runner/go/pkg/mod/
          key: GO_MOD_CACHE
      - name: Test
        run: go test -v --race -coverprofile cover.out ./...
      - name: Format coverage
        run: go tool cover -html=cover.out -o coverage.html
      - name: Upload coverage to Artifacts
        uses: actions/upload-artifact@v2.2.2
        with:
          name: coverage_artifacts
          path: coverage.html
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Cache
        uses: actions/cache@v2.1.6
        with:
          path: |
            /home/runner/.cache/go-build/
            /home/runner/go/pkg/mod/
          key: GO_MOD_CACHE
      - name: Build amd64
        run: |
          GOOS=linux GOARCH=amd64 ./build.sh
      - name: Upload a Build Artifacts
        uses: actions/upload-artifact@v2.2.2
        with:
          name: build_artifacts
          path: |
            yd-go
  push:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Artifacts
        uses: actions/download-artifact@v2.0.8
        with:
          name: build_artifacts
      - name: Upload to release assets
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          file: 'yd-go'
          draft: false
          verbose: true
          overwrite: true
